events {

}
http {
    
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name _;

        #create frontend folder in your nginx.conf directory
        root /etc/nginx/frontend;
    }
}